server:
  port: 1024
max-http-header-size: 1048576
  tomcat: 
    max-http-post-size: 1048576
spring:
  application:
    name: application-common
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true