server:
  port: 1299
spring:
  application:
    name: zuul-service
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/**
      serviceId: plat-service
    product:
      path: /product/**
      serviceId: product-service
    common:
      path: /common/**
      serviceId: common-service
  prefix: /services