server:
  port: 1299
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true #使用ip注册到eureka服务列表
spring:
  application:
    name: zuul-service
zuul:
  ignoredServices: '*'
  routes:
    plat:
      path: /plat/**
      serviceId: plat-service
  prefix: /services